### ISSUE TITLE
Add Privacy Policy page

### ISSUE THREAD

**Issue by felipebueno** [klauswuestefeld/percival-frontend#10]

**Comment by felipebueno** [comment]
Fala @israel-jux!

O @klauswuestefeld disse que você pode nos ajudar nisso :grin:

**Comment by israel-jux** [comment]
Há!

Tá na mão - https://www.percival.live/privacidade?lang=pt

**Comment by kauwai** [comment]
@israel-jux tem a versão em inglês dessa página? Tentamos trocar o lang para "en", mas não funcionou.

**Comment by israel-jux** [comment]
@kauwai @felipebueno versão final - https://www.percival.live/privacy

A estrutura do site é que pra tudo que é em inglês não tenha "en" e tudo que seja em portugues tenha "?lang=pt"

Ou seja, nossa lingua pricipal no site é o inglês.

Páginas que fogem dessa regra são as landing pages como a do RH Agil, como não existe a versão em EN não tem o 
"?lang=pt" - ex: https://www.percival.live/rh-agil

**Comment by kauwai** [comment]
@israel-jux tudo certo, enviado para o site em produção!
